<?php
session_start();
$_SESSION=array();
if(isset($_COOKIE[session_name()])==ture){
  setcookie(session_name(),'',time()-42000,'/');
}
session_destroy();
header('Location:index.php?member_logout=1');
exit();
?>
